sonar.projectKey=Piedra-Azul
sonar.projectName=Piedra Azul
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000

# Rutas
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.js

# Backend Java
sonar.java.binaries=piedraAzul-back/target

# Encoding
sonar.sourceEncoding=UTF-8