server.port=8080
spring.application.name=piedrazul-appointments

# BASE DE DATOS H2
spring.datasource.url=jdbc:h2:file:./data/piedrazul
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# KEYCLOAK
keycloak.server-url=http://localhost:8180
keycloak.realm=piedrazul
keycloak.admin-username=admin
keycloak.admin-password=admin
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8180/realms/piedrazul/protocol/openid-connect/certs}